apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend-deployment
  labels:
    app: go-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: gcr.io/repo-backend/goserver:v1
        ports:
        - containerPort: 3000
